### ISSUE TITLE
Colors from colorful palette aren't showed properly in Mac terminal

### ISSUE THREAD

**Issue by m-lukas** [gonvenience/bunt#10]
Using the `colorful.WarmPalette()` function and creating colored strings using `bunt.Style(..., bunt.Foreground(color), bunt.Bold())`, it doesn't show many colors, especially darker colors properly in termanal but displays Grey instead. I'm using the standart MacOS terminal in vscode and Zsh.

![Screenshot 2019-07-11 at 11 40 36](https://user-images.githubusercontent.com/17454617/61040408-c844fc00-a3d0-11e9-86f2-bcc5020073da.png)

Raw-Output:
`0
#8d5635
1
#586a34
2
#553641
3
#4a3d24
4
#7f5b45
5
#632c4e
6
#3e6a83
7
#675624
8
#234953
9
#7b5959
10
#8c4f6e
11
#60654b
12
#336d4b
13
#284733
14
#63331b
15
#954f51
16
#456194
17
#463665
18
#2f4818
19
#356d6a
20
#324160
21
#765588
22
#6b2b31
23
#6c5c77`

**Comment by HeavyWombat** [comment]
I used the colors you provided and created two screenshots in the terminal applications I have. It is really the fact that the macOS terminal app does not support 24 bit colors the way iTerm2 is doing it. The `bunt` package tries to use the 4 bit equivalent fall back colors.

| macOS default terminal app   |      iTerm2 terminal macOS      |  
|----------|-------------|
| <img height="640" alt="image" src="https://user-images.githubusercontent.com/1979133/61108026-8fb12b00-a481-11e9-93ad-453ac0d8fbf9.png"> |  <img height="640" alt="image" src="https://user-images.githubusercontent.com/1979133/61108109-c5561400-a481-11e9-936b-41065503f154.png"> |
